const guides=[
 {id:1,title:'كيف تعمل جرد مخزن من غير ما توقف الشغل؟',category:'الجرد',date:'12 أغسطس 2026',time:'8 دقائق',desc:'طريقة عملية لتقسيم الجرد وتسجيل الفروقات والوصول لرصيد يمكن الاعتماد عليه.',thumb:'audit',icon:'⌁'},
 {id:2,title:'ملف Excel بسيط لمتابعة الوارد والمنصرف',category:'Excel',date:'07 أغسطس 2026',time:'11 دقيقة',desc:'ابنِ جدولًا واضحًا يبدأ من حركة الصنف وينتهي بقرار شراء أفضل.',thumb:'excel',icon:'▦'},
 {id:3,title:'5 أخطاء بتاكل ربح المخزن من غير ما تحس',category:'الربحية',date:'02 أغسطس 2026',time:'6 دقائق',desc:'نراجع الأخطاء الشائعة في الهالك والتسعير وتسجيل المرتجعات.',thumb:'stock',icon:'↗'},
 {id:4,title:'دورة الصنف داخل المخزن من أول الاستلام للبيع',category:'إدارة المخازن',date:'28 يوليو 2026',time:'9 دقائق',desc:'افهم حركة الصنف كاملة وحدد نقطة التأخير أو الفقد.',thumb:'stock',icon:'◈'},
 {id:5,title:'متى تستخدم الحد الأدنى لإعادة الطلب؟',category:'إدارة المخازن',date:'21 يوليو 2026',time:'7 دقائق',desc:'قاعدة سهلة تساعدك تشتري في الوقت المناسب بدون تكديس أو نفاد.',thumb:'audit',icon:'!'}
];
const courses=[{id:1,title:'أساسيات إدارة المخازن للمبتدئين',lessons:12,duration:'4 ساعات',level:'مبتدئ',icon:'▦',desc:'مسار عملي يبدأ من تعريف الصنف وينتهي بجرد مرتب.'},{id:2,title:'Excel للمخازن من الصفر',lessons:9,duration:'3 ساعات',level:'مبتدئ',icon:'⌁',desc:'ابنِ جداول متابعة مفهومة واستخدمها كل يوم.'},{id:3,title:'تقليل الهالك وزيادة الربحية',lessons:7,duration:'ساعتان',level:'متوسط',icon:'↗',desc:'حوّل أرقام المخزن إلى خطة تقلل الخسارة.'}];
const $=s=>document.querySelector(s), $$=s=>[...document.querySelectorAll(s)];
let filter='all',query='',visible=3;
function stored(key,fallback){try{return JSON.parse(localStorage.getItem(key))||fallback}catch{return fallback}}
function renderGuides(){const list=$('#guideList'), empty=$('#guideEmpty'), load=$('#loadMore');const items=stored('makhazni-guides',guides).filter(x=>(filter==='all'||x.category===filter)&&`${x.title} ${x.desc} ${x.category}`.toLowerCase().includes(query.toLowerCase()));const view=items.slice(0,visible);list.innerHTML=view.map(x=>`<article class="guide-card"><div class="thumb ${x.thumb}">${x.icon}</div><div class="guide-copy"><h3>${x.title}</h3><p>${x.desc}</p><div class="guide-meta"><span class="guide-tag">${x.category}</span><span>${x.date}</span><span>${x.time}</span></div></div><button class="guide-action" data-guide="${x.id}">اقرأ الشرح</button></article>`).join('');empty.hidden=items.length>0;list.hidden=items.length===0;load.hidden=view.length>=items.length||!items.length}
function renderCourses(){$('#courseList').innerHTML=courses.slice(1).map(x=>`<article class="course-row"><div class="course-cover">${x.icon}</div><div><h3>${x.title}</h3><p>${x.lessons} دروس، ${x.duration}، ${x.level}</p></div><button data-course="${x.id}">عرض التفاصيل ←</button></article>`).join('')}
function openDialog(html){$('#dialogContent').innerHTML=html;$('#dialog').showModal()}
function guideDetails(id){const x=guides.find(i=>String(i.id)===String(id));if(x)openDialog(`<p class="eyebrow">${x.category}</p><h2>${x.title}</h2><p>${x.desc}</p><p>شرح مرتب وأمثلة عملية تساعدك تطبق الفكرة على مخزنك بدل ما تفضل مجرد معلومة.</p><div class="dialog-meta">${x.date} · ${x.time}</div>`)}
function courseDetails(id){const x=courses.find(i=>String(i.id)===String(id));if(x)openDialog(`<p class="eyebrow">${x.level}</p><h2>${x.title}</h2><p>${x.desc}</p><div class="dialog-meta">${x.lessons} دروس · ${x.duration}</div>`)}
$('#guideSearch').addEventListener('input',e=>{query=e.target.value.trim();visible=3;renderGuides()});$('#guideFilters').addEventListener('click',e=>{const b=e.target.closest('[data-filter]');if(!b)return;filter=b.dataset.filter;visible=3;$$('.filter').forEach(x=>x.classList.toggle('active',x===b));renderGuides()});$('#loadMore').addEventListener('click',()=>{visible+=3;renderGuides()});$('#guideList').addEventListener('click',e=>{const b=e.target.closest('[data-guide]');if(b)guideDetails(b.dataset.guide)});$('#courseList').addEventListener('click',e=>{const b=e.target.closest('[data-course]');if(b)courseDetails(b.dataset.course)});$$('[data-course="1"]').forEach(b=>b.addEventListener('click',()=>courseDetails(1)));$('#closeDialog').addEventListener('click',()=>$('#dialog').close());$('#dialog').addEventListener('click',e=>{if(e.target.id==='dialog')$('#dialog').close()});
const menu=$('#mainNav'),toggle=$('.menu-toggle');toggle.addEventListener('click',()=>{const open=menu.classList.toggle('open');toggle.setAttribute('aria-expanded',open)});menu.addEventListener('click',e=>{if(e.target.matches('a'))menu.classList.remove('open')});
function normalizePhone(value){const digits=value.replace(/\D/g,'');return digits.startsWith('01')?'20'+digits.slice(1):digits}
$('#consultForm').addEventListener('submit',e=>{e.preventDefault();const data=new FormData(e.currentTarget),phone=normalizePhone(String(data.get('phone'))),status=$('#consultStatus');if(!/^20\d{10}$/.test(phone)){status.textContent='اكتب رقم واتساب مصري صحيح، مثال: 01012345678.';return}const msg=['مرحباً مصطفى، أريد حجز استشارة من موقع مخزني.',`الاسم: ${data.get('name')}`,`نوع الاستشارة: ${data.get('type')}`,`التاريخ: ${data.get('date')}`,`التفاصيل: ${data.get('details')}`].join('\n');window.open(`https://wa.me/${phone}?text=${encodeURIComponent(msg)}`,'_blank','noopener,noreferrer');status.textContent='تم تجهيز الرسالة وفتح واتساب. راجعها واضغط إرسال.';status.className='status ok'});
$('#copyPayment').addEventListener('click',async()=>{const b=$('#copyPayment');try{await navigator.clipboard.writeText('01112876080');b.textContent='تم النسخ'}catch{b.textContent='01112876080'}setTimeout(()=>b.textContent='نسخ الرقم',1600)});
const paid=$('#paymentConfirmed'), ref=$('#paymentReference'), download=$('#downloadButton'), gate=$('#gateStatus'), downStatus=$('#downloadStatus');function updateGate(){const ready=paid.checked&&ref.value.trim().length>2;download.disabled=!ready;gate.textContent=ready?'تم تأكيد الدفع. يمكنك التحميل الآن.':'أكّد الدفع واكتب رقم العملية أولًا.';gate.className=ready?'ready':'';downStatus.textContent=ready?'الدفع مؤكد، اضغط لتحميل الإكسل.':'التحميل مقفول حتى تأكيد الدفع.'}paid.addEventListener('change',updateGate);ref.addEventListener('input',updateGate);
const workbook=`<?xml version="1.0"?><Workbook xmlns="urn:schemas-microsoft-com:office:spreadsheet" xmlns:ss="urn:schemas-microsoft-com:office:spreadsheet"><Styles><Style ss:ID="Title"><Font ss:Bold="1" ss:Size="16"/><Interior ss:Color="#b9f0df" ss:Pattern="Solid"/></Style><Style ss:ID="Header"><Font ss:Bold="1"/><Interior ss:Color="#b9f0df" ss:Pattern="Solid"/></Style></Styles><Worksheet ss:Name="تعليمات"><Table><Row><Cell ss:StyleID="Title"><Data ss:Type="String">النظام المتكامل لإدارة المخازن</Data></Cell></Row><Row><Cell><Data ss:Type="String">أدخل البيانات في الأوراق المخصصة ثم راجع لوحة الجرد.</Data></Cell></Row></Table></Worksheet><Worksheet ss:Name="مخزن الخامات"><Table><Row><Cell ss:StyleID="Header"><Data ss:Type="String">التاريخ</Data></Cell><Cell ss:StyleID="Header"><Data ss:Type="String">اسم الخامة</Data></Cell><Cell ss:StyleID="Header"><Data ss:Type="String">الوارد</Data></Cell><Cell ss:StyleID="Header"><Data ss:Type="String">المنصرف</Data></Cell><Cell ss:StyleID="Header"><Data ss:Type="String">الرصيد</Data></Cell></Row></Table></Worksheet><Worksheet ss:Name="المنتج التام"><Table><Row><Cell ss:StyleID="Header"><Data ss:Type="String">التاريخ</Data></Cell><Cell ss:StyleID="Header"><Data ss:Type="String">اسم المنتج</Data></Cell><Cell ss:StyleID="Header"><Data ss:Type="String">الإنتاج</Data></Cell><Cell ss:StyleID="Header"><Data ss:Type="String">المبيعات</Data></Cell><Cell ss:StyleID="Header"><Data ss:Type="String">الرصيد الحالي</Data></Cell></Row></Table></Worksheet><Worksheet ss:Name="سجل المبيعات"><Table><Row><Cell ss:StyleID="Header"><Data ss:Type="String">التاريخ</Data></Cell><Cell ss:StyleID="Header"><Data ss:Type="String">العميل</Data></Cell><Cell ss:StyleID="Header"><Data ss:Type="String">المنتج</Data></Cell><Cell ss:StyleID="Header"><Data ss:Type="String">الكمية</Data></Cell><Cell ss:StyleID="Header"><Data ss:Type="String">المرتجع</Data></Cell></Row></Table></Worksheet><Worksheet ss:Name="لوحة الجرد"><Table><Row><Cell ss:StyleID="Header"><Data ss:Type="String">الصنف</Data></Cell><Cell ss:StyleID="Header"><Data ss:Type="String">الكود</Data></Cell><Cell ss:StyleID="Header"><Data ss:Type="String">الرصيد الحالي</Data></Cell><Cell ss:StyleID="Header"><Data ss:Type="String">الحالة</Data></Cell></Row></Table></Worksheet></Workbook>`;
download.addEventListener('click',()=>{if(download.disabled)return;const url=URL.createObjectURL(new Blob([workbook],{type:'application/vnd.ms-excel;charset=utf-8'}));const a=document.createElement('a');a.href=url;a.download='نظام-إدارة-المخازن-110-جنيه.xls';document.body.appendChild(a);a.click();a.remove();setTimeout(()=>URL.revokeObjectURL(url),800);downStatus.textContent='تم تجهيز ملف Excel وبدأ التحميل.'});
$('#receiptForm').addEventListener('submit',e=>{e.preventDefault();const data=new FormData(e.currentTarget),phone=normalizePhone(String(data.get('customerPhone'))),status=$('#receiptStatus');if(!/^20\d{10}$/.test(phone)){status.textContent='اكتب رقم واتساب مصري صحيح، مثال: 01012345678.';return}const msg=['مرحباً '+data.get('customerName'),'','إيصال تأكيد الدفع','المنتج: قالب إدارة المخازن','قيمة التحويل: '+data.get('amount'),'رقم العملية: '+data.get('reference'),'التاريخ: '+new Intl.DateTimeFormat('ar-EG',{dateStyle:'medium',timeStyle:'short'}).format(new Date()),'','شكراً لك، فريق مخزني'].join('\n');window.open(`https://wa.me/${phone}?text=${encodeURIComponent(msg)}`,'_blank','noopener,noreferrer');status.textContent='تم تجهيز الإيصال وفتح واتساب. راجع الرسالة واضغط إرسال.';status.className='status ok'});
window.MakhzaniContent={addGuide(item){item.id=Date.now();const old=stored('makhazni-guides',guides);localStorage.setItem('makhazni-guides',JSON.stringify([item,...old]));renderGuides()},addCourse(item){item.id=Date.now();const old=stored('makhazni-courses',courses);localStorage.setItem('makhazni-courses',JSON.stringify([item,...old]));renderCourses()}};
$('#year').textContent=new Date().getFullYear();renderGuides();renderCourses();
